### ISSUE TITLE
Support etcdv3

### ISSUE THREAD

**Issue by vladimirtiukhtin** [rabbitmq/rabbitmq-peer-discovery-etcd#13]
Hello

Is there a way to use v3 API in the plugin? Thanks

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
From the [documentation guide on cluster formation](http://www.rabbitmq.com/cluster-formation.html#peer-discovery-etcd):

> etcd v3 and v2 are supported.

**Comment by vladimirtiukhtin** [comment]
@michaelklishin hi. Thanks you for the reply. Unfortunately in fact etcd v3 is not supported. RabbitMQ connects to etcd via v2 in any case

**Comment by michaelklishin** [comment]
I have been running etcd 3 with this plugin for many months now. That counts for "etcd3 support" for me. If you have a different definition then please explicitly state what it is and explain why our tiny team should spend time on it. Or contribute a PR since the plugin is pretty small and doesn't do anything sophisticated.

Our team does not use GitHub issues for discussions. Your suggestions are welcome on our mailing list.

**Comment by michaelklishin** [comment]
etcd v3 API support will ship in `3.8.4`, see https://github.com/rabbitmq/rabbitmq-peer-discovery-etcd/issues/22.
