### ISSUE TITLE
Connections to etc fail when it performs TLS peer authentication

### ISSUE THREAD

**Issue by livius-ungureanu** [rabbitmq/rabbitmq-peer-discovery-etcd#23]
Steps to reproduce:

Given the following config in rabbitmq.conf:

```
cluster_partition_handling = pause_minority
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_etcd
cluster_formation.etcd.host = 10.232.122.160
cluster_formation.etcd.port = 4011
cluster_formation.etcd.scheme = https
ssl_options.certfile = /etc/ssl/cert.pem
ssl_options.keyfile = /etc/ssl/key.pem
ssl_options.cacertfile = /etc/ssl/ca-certs.pem
```
Then when the RabbitMQ node tries to join the cluster(i.e. connects to etcd which is mutulTls secured),  TLS handshake fails because RabbitMQ does not provide its identity certificate:

Proof:

1) In logs one can notice:

```
2020-03-26 22:13:55.510 [debug] <0.12225.0> Response: [{error,{failed_connect,[{to_address,{"10.232.122.160",4011}},{inet,[inet],{tls_alert,{bad_certificate,"TLS client: In state cipher received SERVER ALERT: Fatal - Bad Certificate\n "}}}]}}]
```

2)  This is visible also in wireshark:
![image](https://user-images.githubusercontent.com/31243250/77733455-941d7400-700f-11ea-8b89-bfe6ec091134.png)

3) I trust the certs are valid since if I simulate RBMQ's expected TLS behavior with 

```
openssl s_client  -connect  10.232.122.160:4011   -CAfile  /etc/ssl/ca-certs.pem -cert /etc/ssl/cert.pem  -key  /etc/ssl/key.pem
```
then the TLS handshake is successful.

Net: In the attached screen capture, one can notice in the  highlighted packet (5814) that RBMQ does not sent its identity cert(as specified by `ssl_options.certfile = /etc/ssl/cert.pem`) to etcd even in packet 5811 ectd responded to RabbitMQ with "Certificate Request" which RabbitMq does not honor.

**Comment by michaelklishin** [comment]
Please don't ask the same question in multiple places (on rabbitmq-users and here).

The error says that the server [refuses to trust the client](https://www.rabbitmq.com/ssl.html#peer-verification) and very likely because the client hasn't provided any certificate (it does not do so by default).

Current etcd client is an HTTP one so configuring TLS certificates for it is a matter of configuring them for that client. We will try to put together an example and post it on the mailing list.

However, all of this will go away as soon as #22 lands with a completely new etcd client. I will file a new issue for TLS options even though it wouldn't be forgotten anyway.

**Comment by michaelklishin** [comment]
Unfortunately for everyone, TLS is used in many contexts and what `ssl_options.certfile` and so on configure is the server certificate for AMQP 0-9-1, AMQP 1.0, MQTT and STOMP clients. Peer discovery here acts as a *TLS client* so while we could reuse these settings, it's a completely different code path and context, and not everyone would agree that it's a good idea.
